const ADD_TASK_IN_LIST = "ADD_TASK_IN_LIST";
const DELETE_TASK = "DELETE_TASK";
const EDIT_TASK ="EDIT_TASK";
const COMPLETE_TASK ="COMPLETE_TASK"


export { ADD_TASK_IN_LIST, DELETE_TASK, EDIT_TASK, COMPLETE_TASK   }